name: Patch and Build

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Configure Git User Details
        run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
      - name: Apply Patches
        run: ./gradlew applyAllPatches --stacktrace --scan
      - name: Build
        run: ./gradlew build --scan
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
      - name: Bundle
        run: ./gradlew createMojmapPaperclipJar
      - name: Upload bundle
        uses: actions/upload-artifact@v4.6.0
        with:
          name: paperclip-bundle
          path: cuneiform-server/build/libs/cuneiform-paperclip-*-*-SNAPSHOT-mojmap.jar
          if-no-files-found: error
      - name: Create Release
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: |
          sha_short=$(git rev-parse --short HEAD)
          version=$(ls cuneiform-server/build/libs/cuneiform-paperclip-*-*-SNAPSHOT-mojmap.jar | grep -o '[[:digit:]]\+\.[[:digit:]]\+\.[[:digit:]]\+')
          gh release create --draft "v$version+$sha_short" --title "$version+$sha_short"
          gh release upload "v$version+$sha_short" $(ls cuneiform-server/build/libs/cuneiform-paperclip-*-*-SNAPSHOT-mojmap.jar)
          gh release edit "v$version+$sha_short" --draft=false

